//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Page.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialProd
    {
        public MaterialProd()
        {
            this.Material = new HashSet<Material>();
        }
    
        public int id { get; set; }
        public string NameMaterials { get; set; }
    
        public virtual ICollection<Material> Material { get; set; }
    }
}
