//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Page.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public Material()
        {
            this.MaterialsAndProducts = new HashSet<MaterialsAndProducts>();
            this.Product = new HashSet<Product>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public int id_Type { get; set; }
        public Nullable<int> CountPackaged { get; set; }
        public string Unit { get; set; }
        public Nullable<int> CountStocked { get; set; }
        public Nullable<int> MinimumBalance { get; set; }
        public Nullable<decimal> Cost { get; set; }
    
        public virtual MaterialProd MaterialProd { get; set; }
        public virtual ICollection<MaterialsAndProducts> MaterialsAndProducts { get; set; }
        public virtual ICollection<Product> Product { get; set; }
    }
}
