//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Page.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.MaterialsAndProducts = new HashSet<MaterialsAndProducts>();
        }
    
        public int Id_Prod { get; set; }
        public string Name { get; set; }
        public Nullable<int> MinCostForAgent { get; set; }
        public byte[] Picture { get; set; }
        public int Id_Type { get; set; }
        public Nullable<int> Count { get; set; }
        public int Id_Material { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual ICollection<MaterialsAndProducts> MaterialsAndProducts { get; set; }
        public virtual TypeProd TypeProd { get; set; }
    }
}
